name: Deploy development

on:
  push:
    branches:
      - develop

env:
  STAGE: dev
  AWS_REGION: us-east-1

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} ⚙
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile
      - name: Serverless deploy 🚀
        uses: serverless/github-action@v3
        with:
          args: deploy --stage ${{ env.STAGE }} --region ${{ env.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
